spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/replication_test?ssl=false
    username: "root"
    password: "rootpassword"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    #OAuth2
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email
            redirect-uri: "{baseUrl}/auth/google/callback"
            authorization-grant-type: authorization_code
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            scope: name, email
            redirect-uri: "{baseUrl}/auth/naver/callback"
            authorization-grant-type: authorization_code
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            scope: account_email
            redirect-uri: "{baseUrl}/auth/kakao/callback"
            authorization-grant-type: authorization_code
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: id
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  spring-doc:
    swagger-ui:
      path: /swagger-ui.html  # Swagger UI에 접근할 경로
    api-docs:
      path: /v3/api-docs      # OpenAPI 명세서를 제공할 경로
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#api:
#  crime:
#    url: https://api.odcloud.kr/api/3074462/v1/uddi:efafd73f-3310-48f8-9f56-bddc1c51f3ba_201910221541?serviceKey=5IiT10w5sPxfnjD0lHu9Zf5Fe%2Fkc64s6mKIH9G%2FPKKBOlK47wIOrlHX3bM6xCQFTHGwjkZw5uC1eDyPRrF5Wcg%3D%3D&page=1&perPage=10
#    key: ${CRIME_API_KEY}
